from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('afficher',views.afficher,name='afficher'),
    path('getallusers',views.GetAllUsers,name='getallusers'),
    path('acceuil',views.Acceuil,name='acceuil'),
    path('choiceA1',views.ChoiceA1,name='choiceA1'),
    path('choiceA2',views.ChoiceA2,name='choiceA2'),
    path('choiceB1',views.ChoiceB1,name='choiceB1'),
    path('choiceB2',views.ChoiceB2,name='choiceB2'),
    path('login',views.Login,name='login'),
    path('signup',views.Signup,name='signup'),
    path('saveuser',views.SaveUser,name='saveuser'),
    path('savemessage',views.SaveMessage,name='savemessage'),
    path('modulA1',views.ModulA1,name='modulA1'),
    path('modulA2',views.ModulA2,name='modulA2'),
    path('modulB1',views.ModulB1,name='modulB1'),
    path('modulB2',views.ModulB2,name='modulB2'),
    path('connexion', views.Connexion, name='connexion'),
    path('deletuser', views.deletuser, name='deletuser'),
    path('courspageA1', views.CoursPageA1, name='courspageA1'),
    path('courspageA2', views.CoursPageA2, name='courspageA2'),
    path('courspageB1', views.CoursPageB1, name='courspageB1'),
    path('courspageB2', views.CoursPageB2, name='courspageB2'),
    path('grammatikA1', views.GrammatikA1, name='grammatikA1'),
    path('grammatikA2', views.GrammatikA2, name='grammatikA2'),
    path('grammatikB1', views.GrammatikB1, name='grammatikB1'),
    path('grammatikB2', views.GrammatikB2, name='grammatikB2'),
    path('nummerA1', views.NummerA1, name='nummerA1'),
    path('alphabetA1', views.AlphabetA1, name='alphabetA1'),
    path('pronomA1', views.PronomA1, name='pronomA1'),
    path('adverbA2', views.AdverbA2, name='adverbA2'),
    path('verbA2', views.VerbA2, name='verbA2'),
    path('adjektivA2', views.AdjektivA2, name='adjectivA2'),
    path('schreibenA1', views.SchreibenA1, name='schreibenA1'),
    path('schreibenA2', views.SchreibenA2, name='schreibenA2'),
    path('schreibenB1', views.SchreibenB1, name='schreibenB1'),
    path('schreibenB2', views.SchreibenB2, name='schreibenB2'),
    path('prepositionB1', views.PrepositionB1, name='prepositionB1'),
    path('syntaxeB1', views.SyntaxeB1, name='syntaxeB1'),
    path('subB2', views.SubB2, name='subB2'),
    path('verbB1', views.VerbB1, name='verbB1'),
    path('verneinungB2', views.VerneinungB2, name='VerneinungB2'),
    path('horenA1', views.HorenA1, name='horenA1'),
    path('LesenA1', views.LesenA1, name='LesenA1'),
    path('LesenB2', views.LesenB2, name='LesenB2'),
]